# Generated by Django 4.2.13 on 2024-08-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stocklevel',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products_images/'),
        ),
    ]
